---
title: "Comparing Simulations to Actual Data - Gabon Case Study"
author: "Aditya Ramani"
date: "2023-06-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(7281998)
library(dplyr)
library(ggplot2)
library(tidyr)
library(fastR2)
library(stringr)
library(gtable)
library(knitr)
library(kableExtra)
library(gridExtra)
library(patchwork)
library(ggrepel)
library(readxl)
knitr::knit_hooks$set(timeit = local({
  now = NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res = difftime(Sys.time(), now)
      now <<- NULL
      # use options$label if you want the chunk label as well
      paste('Time for this code chunk:', as.character(res))
    }
  }})
)
simulateRDT=TRUE
output_version = "v3"
```

## Actual Data

```{r basic_read_functions, timeit=TRUE}
readGabonData <- function() {
  fileName <- "../../RVC/Improving Ov16/Ov16 Data/Skin_snip_and_Ov16_RDT_and_Ov16_ELISA_data_Gabon_2015.xlsx"
  sheets <- excel_sheets(fileName)
  data <- read_excel(fileName, sheet=sheets[1])
  #data <- read.csv(fileName, check.names = FALSE)
  #cols_to_keep <- c(2, 8, 9, 10, 14, 16, 17, 20, 21, 33, 34)
  #data <- data[,cols_to_keep]
  data <- data %>% mutate(
    ov16_seropos = case_when(
      get("Ov16 result") == 1 ~ 1,
      is.na(get("Ov16 result")) ~ NA, # ~ NA,
      TRUE ~ 0
      ),
    mf_pos = ifelse(Oncho_MF_mean_by_snip > 0, 1, 0),
    sex = case_when(
      get("Sex (1=M, 2=F)") == 1 ~ 'Male',
      get("Sex (1=M, 2=F)") == 2 ~'Female',
      TRUE ~ as.character(NA)),
    age_groups = case_when(
      Age == 0 ~ 0,
      Age <= 30 ~ (ceiling(Age/5)*5) - 2.5,
      Age <= 75 ~ (ceiling(Age/5)*5) - 2.5,
      TRUE ~ 77.5
    )
  ) %>% filter(!is.na(mf_pos) & !is.na(ov16_seropos)) #filter(!is.na(ov16_seropos))
  
  print(paste("Total Individuals:", length(unique(data$Individual_ID))))
  print(paste("Male to Female Ratio:", mean(((data[,'Sex (1=M, 2=F)']-2)*-1))))
  print(paste("Overall Gabon MF Prevalence:", mean(data$mf_pos)))
  print(paste("Overall Gabon Ov16 SeroPrevalence:", mean(data$ov16_seropos)))
  print(paste("5+ Gabon MF Prevalence:", 
              mean(data[data$Age >= 5,'mf_pos']$mf_pos, na.rm=TRUE),
              wilson.ci(sum(data[data$Age >= 5,'mf_pos']$mf_pos, na.rm=TRUE), length(data[data$Age >= 5,'mf_pos']$mf_pos))[1],
              "-", 
              wilson.ci(sum(data[data$Age >= 5,'mf_pos']$mf_pos, na.rm=TRUE), length(data[data$Age >= 5,'mf_pos']$mf_pos))[2]))
  print(paste("5+ Gabon Ov16 SeroPrevalence:", mean(data[data$Age >= 5,]$ov16_seropos, na.rm=TRUE),
              wilson.ci(sum(data[data$Age >= 5,'ov16_seropos']$ov16_seropos, na.rm=TRUE), length(data[data$Age >= 5,'ov16_seropos']$ov16_seropos))[1],
              "-", 
              wilson.ci(sum(data[data$Age >= 5,'ov16_seropos']$ov16_seropos, na.rm=TRUE), length(data[data$Age >= 5,'ov16_seropos']$ov16_seropos))[2]
              ))
  
  returnVal <- list(data, mean(data$mf_pos))
  names(returnVal) <- c("data", "mf_prev")
  return(returnVal)
}

readGabonMultiCountryVillageGroupedData <- function() {
  fileName <- "../../RVC/Improving Ov16/Ov16 Data/Ov16_Gabon_all_results_by_village.csv"
  data <- read.csv(fileName)
  df <- data.frame(mf_pos=data$MF.Positive, mf_neg=data$MF.Negative, rdt_pos=data$Ov16.RDT.Positive, total_ind=data$Total, ov_pos_mf_pos=data$Ov16.Pos..MF.Pos, ov_neg_mf_neg=data$Ov16.Neg..MF.neg)
  total_data <- df %>% summarise(across(1:4, sum))
  print(paste("Total Individuals:", total_data$total_ind))
  print(paste("Total Mf Pos:", total_data$mf_pos))
  print(paste("Total Ov16 Pos:", total_data$rdt_pos))
  print(paste("Total MFP:", total_data$mf_pos/total_data$total_ind,
              wilson.ci(total_data$mf_pos, total_data$total_ind, conf.level = 0.95)[1], 
              wilson.ci(total_data$mf_pos, total_data$total_ind, conf.level = 0.95)[2]))
  print(paste("Total Ov16 Prev:", total_data$rdt_pos/total_data$total_ind,
              wilson.ci(total_data$rdt_pos, total_data$total_ind, conf.level = 0.95)[1], 
              wilson.ci(total_data$rdt_pos, total_data$total_ind, conf.level = 0.95)[2]))
  return(df)
}

readGabonDataRDTElisa <- function() {
  fileName <- "../../RVC/Improving Ov16/Ov16 Data/Ov16 Gabon ELISA.csv"
  data <- read.csv(fileName) %>% dplyr::select(1:14) %>% drop_na()
  colnames(data) <- c('id', 'ov16_status_rdt', 'mf_status', 'sample_id', 'inferred_conc', 'region', 'district_name', 'village_name', 'ov16_elisa_plate_num', 'sample_id_ind_id_mismatch', 'ov16_result_elisa', 'ov16_status_elisa', 'age', 'age_group_orig')
  # view duplicate individual id vals, remove them as we don't know which one is correct
  dupIds <- as.numeric(names(which(table(data$id) > 1)))
  data[data$id %in% dupIds,]
  data <- data %>% filter(!(id %in% dupIds)) %>% filter(age >= 5) %>% mutate(
    age_groups = case_when(
      age == 0 ~ 0,
      age <= 30 ~ (ceiling(age/5)*5) - 2.5,
      age <= 75 ~ (ceiling(age/5)*5) - 2.5,
      TRUE ~ 77.5
    ),
    ov16_status_elisa = case_when(
      ov16_result_elisa == 'Invalid' ~ as.numeric(NaN),
      TRUE ~ as.numeric(ov16_status_elisa)
    )
  ) %>% drop_na()
  
  mf_ci <- wilson.ci(sum(data$mf_status), length(data$mf_status), conf.level=0.95)
  ov16_ci <- wilson.ci(sum(data$ov16_status_elisa), length(data$ov16_status_elisa), conf.level=0.95)
    print(paste("Total Number of Villages:", length(unique(data$village_name))))
  print(paste("Total Individuals:", length(unique(data$id))))
  print(paste("Overall Gabon MF Prevalence:", mean(data$mf_status), ". 95% Wilson CI: ", mf_ci[1], mf_ci[2]))
  print(paste("Overall Gabon Ov16 ELISA SeroPrevalence:", mean(data$ov16_status_elisa, na.rm=TRUE), ". 95% Wilson CI: ", ov16_ci[1], ov16_ci[2]))
  print(paste("Overall Gabon Ov16 RDT SeroPrevalence:", mean(data$ov16_status_rdt)))
  
  return(data)
}

processActualGabonData <- function(data, justRDT=TRUE, useSex=TRUE) {
  if(justRDT) {
    groupByCols <- c('age_groups')
    if(useSex) {
      groupByCols <- c('age_groups', 'sex')
    }
    data <- data %>% group_by(!!!syms(groupByCols)) %>% summarise(
      ov16_prev_rdt = mean(ov16_seropos),
      mf_prev = mean(mf_pos),
      ov16_wilson_lb = wilson.ci(sum(ov16_seropos), n(), conf.level=0.95)[1],
      ov16_wilson_ub = wilson.ci(sum(ov16_seropos), n(), conf.level=0.95)[2],
      mf_wilson_lb = wilson.ci(sum(mf_pos), n(), conf.level=0.95)[1],
      mf_wilson_ub = wilson.ci(sum(mf_pos), n(), conf.level=0.95)[2],
      n = n(),
      .groups="drop"
    ) %>% as.data.frame() %>% drop_na() %>%
      mutate(
        total_pop = sum(n)
      )
    # fit <- lm(ov16_prev ~ log(age_groups+1), data=data)
    # data[, c('yhat', 'lb', 'ub')] <- predict(fit, list(age_groups=data$age_groups), interval='prediction')
    # ggplot() + geom_point(aes(x=age_groups, y=ov16_prev), color="red", data=summarize_gabon_data_2) +
    #   geom_line(aes(x=age_groups, y=ov16_prev), color="red", data=summarize_gabon_data_2) +
    #   geom_line(aes(x=age_groups, y=yhat), data=summarize_gabon_data_2)
  } else {
    data <- data %>% group_by(age_groups) %>% summarise(
      total_pop = n(),
      ov16_prev_rdt = mean(ov16_status_rdt),
      ov16_prev_elisa = mean(ov16_status_elisa, na.rm=TRUE),
      mf_prev = mean(mf_status),
      ov16_wilson_lb = wilson.ci(sum(ov16_status_elisa), n(), conf.level=0.95)[1],
      ov16_wilson_ub = wilson.ci(sum(ov16_status_elisa), n(), conf.level=0.95)[2],
      mf_wilson_lb = wilson.ci(sum(mf_status), n(), conf.level=0.95)[1],
      mf_wilson_ub = wilson.ci(sum(mf_status), n(), conf.level=0.95)[2],
      n = n(),
      .groups="drop"
    ) %>% as.data.frame() %>%
      mutate(
        total_pop = sum(n)
      )

    # fit <- lm(ov16_prev_rdt ~ log(age_groups+1), data=data)
    # data[, c('yhat_rdt', 'lb_rdt', 'ub_rdt')] <- predict(fit, list(age_groups=data$age_groups), interval='prediction')
    # 
    # fit <- lm(ov16_prev_elisa ~ log(age_groups+1), data=data)
    # data[, c('yhat_elisa', 'lb_elisa', 'ub_elisa')] <- predict(fit, list(age_groups=data$age_groups), interval='prediction')

  }
  data[data$age_groups == 0, c('mf_wilson_lb', 'mf_wilson_ub', 'ov16_wilson_lb', 'ov16_wilson_ub')] <- 0

  data[data$ov16_wilson_lb < 0, 'ov16_wilson_lb'] <- 0
  data[data$mf_wilson_lb < 0, 'mf_wilson_lb'] <- 0
  return(data)
}

```

### Setup and Explore Data

```{r init_act_data, timeit=TRUE}
print("Multicountry RDT Data")
gabon_multiple_country_rdt <- readGabonData()
print("")
print("Gabon ELISA+RDT Data")
gabon_rdt_elisa <- readGabonDataRDTElisa()
print("")
print("Gabon RDT Village Data")
gabon_village_data <- readGabonMultiCountryVillageGroupedData()

if(simulateRDT) {
  summarize_gabon_multicountry_data_sex <- processActualGabonData(gabon_multiple_country_rdt$data)

  summarize_gabon_multicountry_data <- processActualGabonData(gabon_multiple_country_rdt$data, useSex = FALSE)
}

summarized_gabon_rdt_elisa <- processActualGabonData(gabon_rdt_elisa, justRDT=FALSE)


TP = sum(gabon_rdt_elisa$mf_status == 1 & gabon_rdt_elisa$ov16_status_elisa == 1)
TN = sum(gabon_rdt_elisa$mf_status == 0 & gabon_rdt_elisa$ov16_status_elisa == 0)
FN = sum(gabon_rdt_elisa$mf_status == 1 & gabon_rdt_elisa$ov16_status_elisa == 0)
FP = sum(gabon_rdt_elisa$mf_status == 0 & gabon_rdt_elisa$ov16_status_elisa == 1)

print(paste("ELISA: Sens:", TP / (TP + FN)))
print(paste("Spec:", TN / (TN + FP)))


TP <- sum(gabon_multiple_country_rdt$data$mf_pos == 1 & gabon_multiple_country_rdt$data$ov16_seropos == 1)
TN <- sum(gabon_multiple_country_rdt$data$mf_pos == 0 & gabon_multiple_country_rdt$data$ov16_seropos == 0)
FN <- sum(gabon_multiple_country_rdt$data$mf_pos == 1 & gabon_multiple_country_rdt$data$ov16_seropos == 0)
FP <- sum(gabon_multiple_country_rdt$data$mf_pos == 0 & gabon_multiple_country_rdt$data$ov16_seropos == 1)

print(paste("RDT: Sens:", TP / (TP + FN)))
print(paste("Spec:", TN / (TN + FP)))
```

## Simulation Data

```{r simulation_processing_functions}
calcSensSpecSeroPrev <- function(run_seropos_data, sens=1, spec=1, prob=c()) {
  indv <- length(run_seropos_data)
  if(length(prob) < indv) {
    prob <- runif(indv)
  }
  
  if(length(sens) ==0 | is.na(sens)) {
    sens <- 1
  }
  if(length(sens) == 0 | is.na(spec)) {
    spec <- 1
  }
  
  new_seropos_data<-rep(0, indv)
  pos <- which(run_seropos_data==1)
  neg <- which(run_seropos_data==0)

  if(length(pos) > 0) {
    new_seropos_data[pos] <- as.numeric(prob[pos] <= sens)
  }
  if(length(neg) > 0) {
    new_seropos_data[neg] <- as.numeric(prob[neg] > spec)
  }
  return(new_seropos_data)
}

summarizeSimulationDataHelper <- function(data, sensSpec, sensAgeGroup=5) {
  data$probs <- runif(dim(data)[1])
  if(is.data.frame(sensSpec)) {
    data <- data %>% dplyr::group_by(run_num, age_groups) %>%
      #dplyr::summarise(
      mutate(
        ov16_pos=calcSensSpecSeroPrev(ov16_pos, sensSpec[(sensSpec$age_group %in% age_groups) | (sensSpec$age_group %in% (round(age_groups[1]/sensAgeGroup)*sensAgeGroup)), 'sens'][1], sensSpec[(sensSpec$age_group %in% age_groups) | (sensSpec$age_group %in% (round(age_groups[1]/sensAgeGroup)*sensAgeGroup)), 'spec'][1], probs),
        
        ov16_pos_l3=calcSensSpecSeroPrev(ov16_pos_l3, sensSpec[(sensSpec$age_group %in% age_groups) | (sensSpec$age_group %in% (round(age_groups[1]/sensAgeGroup)*sensAgeGroup)), 'sens'][1], sensSpec[(sensSpec$age_group %in% age_groups) | (sensSpec$age_group %in% (round(age_groups[1]/sensAgeGroup)*sensAgeGroup)), 'spec'][1], probs),
        
        ov16_pos_l4=calcSensSpecSeroPrev(ov16_pos_l4, sensSpec[(sensSpec$age_group %in% age_groups) | (sensSpec$age_group %in% (round(age_groups[1]/sensAgeGroup)*sensAgeGroup)), 'sens'][1], sensSpec[(sensSpec$age_group %in% age_groups) | (sensSpec$age_group %in% (round(age_groups[1]/sensAgeGroup)*sensAgeGroup)), 'spec'][1], probs),
        
        ov16_pos_mating_no_mf=calcSensSpecSeroPrev(ov16_pos_mating_no_mf, sensSpec[(sensSpec$age_group %in% age_groups) | (sensSpec$age_group %in% (round(age_groups[1]/sensAgeGroup)*sensAgeGroup)), 'sens'][1], sensSpec[(sensSpec$age_group %in% age_groups) | (sensSpec$age_group %in% (round(age_groups[1]/sensAgeGroup)*sensAgeGroup)), 'spec'][1], probs),
        
        ov16_pos_mating_detectable_mf=calcSensSpecSeroPrev(ov16_pos_mating_detectable_mf, sensSpec[(sensSpec$age_group %in% age_groups) | (sensSpec$age_group %in% (round(age_groups[1]/sensAgeGroup)*sensAgeGroup)), 'sens'][1], sensSpec[(sensSpec$age_group %in% age_groups) | (sensSpec$age_group %in% (round(age_groups[1]/sensAgeGroup)*sensAgeGroup)), 'spec'][1], probs),
        
        ov16_pos_mating_any_mf=calcSensSpecSeroPrev(ov16_pos_mating_any_mf, sensSpec[(sensSpec$age_group %in% age_groups) | (sensSpec$age_group %in% (round(age_groups[1]/sensAgeGroup)*sensAgeGroup)), 'sens'][1], sensSpec[(sensSpec$age_group %in% age_groups) | (sensSpec$age_group %in% (round(age_groups[1]/sensAgeGroup)*sensAgeGroup)), 'spec'][1], probs)
      ) %>% ungroup() %>% as.data.frame()
  } else {
    sens=sensSpec[1]; spec=sensSpec[2]
    if(sens != 1 | spec != 1) {
      data <- data %>% group_by(run_num) %>%
        #summarise(
        mutate(
          ov16_pos=calcSensSpecSeroPrev(ov16_pos, sens, spec, probs),
          ov16_pos_l3=calcSensSpecSeroPrev(ov16_pos_l3, sens, spec, probs),
          ov16_pos_l4=calcSensSpecSeroPrev(ov16_pos_l4, sens, spec, probs),
          ov16_pos_mating_no_mf=calcSensSpecSeroPrev(ov16_pos_mating_no_mf, sens, spec, probs),
          ov16_pos_mating_detectable_mf=calcSensSpecSeroPrev(ov16_pos_mating_detectable_mf, sens, spec, probs),
          ov16_pos_mating_any_mf=calcSensSpecSeroPrev(ov16_pos_mating_any_mf, sens, spec, probs)
        ) %>% ungroup() %>% as.data.frame()
    }
  }
  return(data)
}

summarizeSimulationData <- function(data, sensSpec=c(1,1), groupBySex=TRUE, sensAgeGroup=5) {
  df <- data
  hypothesisNames <- list("Any worm", "L3 exposure", "L4-L5 moult", "Mating worm pair", "Mating worm pair with any mf", "Mating worm pair with detectable mf")
  groupByCols1 <- c("run_num", "age_groups")
  groupByCols2 <- c("age_groups", "Hypothesis")
  hypNamesLoc <- 3:8
  if(groupBySex) {
    groupByCols1 <- c("run_num", "age_groups", "sex")
    groupByCols2 <- c("age_groups", "sex", "Hypothesis")
    hypNamesLoc <- 4:9
  }
  
  df <- summarizeSimulationDataHelper(df, sensSpec, sensAgeGroup)
  
  df <- df %>%
    dplyr::group_by(!!!syms(groupByCols1)) %>%
    dplyr::summarise(ov16_any_worm_prev=mean(ov16_pos),
                     ov16_l3_prev=mean(ov16_pos_l3),
                     ov16_l4_prev=mean(ov16_pos_l4),
                     ov16_mating_no_mf_prev=mean(ov16_pos_mating_no_mf),
                     ov16_mating_any_mf_prev=mean(ov16_pos_mating_any_mf),
                     ov16_mating_detectable_mf_prev=mean(ov16_pos_mating_detectable_mf),
                     num_mf_pos=sum(mf_prev),
                     total_mf=n(),
                     mf_prev=mean(mf_prev), .groups="drop") %>% as.data.frame()
  colnames(df)[all_of(hypNamesLoc)] <- hypothesisNames
  df <- df %>%
    as.data.frame() %>% pivot_longer(cols=all_of(hypNamesLoc), names_to="Hypothesis", values_to = "ov16_prev")

  df <- df %>% dplyr::group_by(!!!syms(groupByCols2)) %>%
    dplyr::summarise(
      ov16_lower = quantile(ov16_prev, probs=0.025),
      ov16_upper = quantile(ov16_prev, probs=0.975),
      ov16_prev=mean(ov16_prev), 
      mf_q1 = quantile(mf_prev, probs=0.025),
      mf_q3 = quantile(mf_prev, probs=0.975),
      mf_prev=mean(mf_prev),
      mf_wilson_lb=wilson.ci(mean(num_mf_pos), mean(total_mf))[1],
      mf_wilson_ub=wilson.ci(mean(num_mf_pos), mean(total_mf))[2], .groups="drop") %>% 
    as.data.frame() %>%
    mutate(
      mf_prev = case_when(
        age_groups == 0 & mf_prev > 0 ~ 0,
        TRUE ~ mf_prev
      ),
      mf_wilson_lb = case_when(
        mf_wilson_lb < 0 ~ 0,
        TRUE ~ mf_wilson_lb
      ),
      mf_wilson_ub = case_when(
        age_groups == 0  ~ 0,
        TRUE ~ mf_wilson_ub
      )
    )

  return(df)
}
calcResidualsMFP <- function(originalData, projection_data) {
  lsr_calculation <- merge(projection_data, originalData, by=c("age_groups")) %>%
    mutate(
      mse_value = (
        (((mf_prev_proj) - (mf_prev*100))**2) *
        n / total_pop
      )) %>%
    select(abr_ke, age_groups, mse_value) %>%
    group_by(abr_ke) %>%
    summarise(mse=sum(mse_value), .groups="drop")
  
  return(lsr_calculation)
}
data_manip_resid_mfp <- function(data) {
  return(
    data %>%
      group_by(abr_ke, run_num, age_groups) %>%
      summarise(
        mf_prev_proj = mean(mf_prev),
        .groups="drop"
      )
  )
}

custom_calc_resid_mfp <- function(original_data, new_data) {
  merged_data <- merge(original_data, new_data, by=c("age_groups"))
  lsr_calculation <- merged_data %>%
    mutate(
      mse_value = (
        ((mf_prev_proj*100) - (mf_prev*100))**2 *
          (n/total_pop)
        )) %>%
    select(abr_ke, run_num, age_groups, mse_value) %>%
    group_by(abr_ke, run_num) %>%
    summarise(mse=sum(mse_value), .groups="drop") %>%
    group_by(abr_ke) %>%
    summarise(mean_mse = mean(mse), .groups="drop")
  return(lsr_calculation)
}
data_manip_resid <- function(data, sens_spec) {
  data$probs <- runif(dim(data)[1])
  return(
    data %>% group_by(run_num) %>% mutate(
      H1=calcSensSpecSeroPrev(ov16_pos_l3, sens_spec[1], sens_spec[2], probs),
      H2=calcSensSpecSeroPrev(ov16_pos_l4, sens_spec[1], sens_spec[2], probs),
      H3=calcSensSpecSeroPrev(ov16_pos, sens_spec[1], sens_spec[2], probs),
      H4=calcSensSpecSeroPrev(ov16_pos_mating_any_mf, sens_spec[1], sens_spec[2], probs)
    ) %>% pivot_longer(
      cols=c(H1, H2, H3, H4), names_to="Hypothesis", values_to = "ov16_prev"
    ) %>% group_by(run_num, age_groups, Hypothesis) %>%
    summarise(
      ov16_prev = mean(ov16_prev),
      .groups="drop"
    )
  )
}

custom_calc_resid <- function(original_data, new_data, desc) {
  merged_data <- merge(original_data, new_data, by=c("age_groups"))
  lsr_calculation <- merged_data %>%
    mutate(
      mse_value = (
        ((ov16_prev*100) - (ov16_prev_rdt*100))**2 *
          (n/total_pop)
        )) %>%
    select(Hypothesis, run_num, age_groups, mse_value) %>%
    mutate(Descriptor = desc) %>% 
    group_by(Hypothesis, run_num, Descriptor) %>%
    summarise(mse=sum(mse_value), .groups="drop")
  return(lsr_calculation)
}

filterHypotheses <- function(data) {
  actual_hyps <- c("Any worm", "L3 exposure", "L4-L5 moult", "Mating worm pair with any mf")
  data <- data %>% filter(Hypothesis %in% actual_hyps) %>% mutate(
    Hypothesis = ifelse(Hypothesis == "Any worm", "Any Adult worm", Hypothesis)
  )
}
```

### Setup and Explore Data

#### ABR vs MFP
```{r}
run_mfp = FALSE
if(run_mfp) {
  summarizeSimulationDataWeightedMFP <- function(projectionData, originalData) {
    data <- projectionData %>% dplyr::select(age, age_groups, sex, mf_prev, ABR, Ke, run_num) %>%
      rename(mf_prev_proj = mf_prev) %>%
      left_join(originalData, by=c("age_groups")) %>%
      group_by(age_groups, ABR, Ke, run_num) %>%
      do(sample_n(., .$n[1], replace = TRUE)) %>%
      ungroup() %>%
      dplyr::select(-ov16_prev_rdt, -mf_prev, -ov16_wilson_lb, -ov16_wilson_ub, -mf_wilson_lb, -mf_wilson_ub, -n, -total_pop)
    return(data)
  }
  gabon_mfp_age_grouped_data_100_sims <- readRDS("data/gabon_agg_data_rdt_mfp_test/gabon_mfp_abr_rdt_data_age_grouped_100_sims.RDS")$allOutputs
  
  gabon_mfp_age_grouped_data_500_sims <- readRDS("data/gabon_agg_data_rdt_mfp_test_500_sims/gabon_mfp_abr_rdt_data_age_grouped_500_sims.RDS")$allOutputs
  
  weighted_mfp_data <- summarizeSimulationDataWeightedMFP(rbind(gabon_mfp_age_grouped_data_100_sims, gabon_mfp_age_grouped_data_500_sims), summarize_gabon_multicountry_data)
  
  mean_weighted_mfp_data <- weighted_mfp_data %>% group_by(ABR, Ke) %>%
    filter(
      age_groups >= 5
    ) %>%
    summarise(
      mf_prev = mean(mf_prev_proj) * 100,
      mf_q1 = quantile(mf_prev_proj, probs=c(0.025)) * 100,
      mf_q3 = quantile(mf_prev_proj, probs=c(0.975)) * 100,
      .groups="drop"
    ) %>%
    mutate(
      abr_ke = paste(ABR, Ke, sep="_"),
      within_bounds = (mf_prev <= 8.7 & mf_prev >= 7.1),
      lb = 7.1,
      ub = 8.7
    )
  
  
  mfp_vs_abr_plot_weighted <- ggplot(data=mean_weighted_mfp_data) + 
    geom_point(aes(x=ABR, y=mf_prev, color=within_bounds)) +
    geom_text_repel(aes(x=ABR, y=mf_prev, color=within_bounds, label=ABR), hjust = -0.5, data=mean_weighted_mfp_data %>% filter(within_bounds), show.legend=FALSE) +
    facet_wrap(~ Ke, scales = "free_x") +
    ylab("Mean microfilarial prevalence (%) at equilibrium") +
    #scale_x_continuous("ABR", sec_axis(~ . , name = expression("k"["E"]), breaks = NULL, labels = NULL)) +
    labs(
      title = expression("Individual exposure heterogeneity " * italic(k)[italic(E)]),
      x = "Annual biting rate"
    ) +
    scale_color_manual("Observed microfilarial prevalence 95% Confidence Interval", values=c("FALSE"="black", "TRUE"="red")) +
    geom_ribbon(aes(x=ABR, ymin=lb, ymax=ub), alpha=0.2, fill="red") +
    #geom_hline(yintercept = 4.81, color="red", alpha=0.5) + 
    #geom_hline(yintercept = 6.57, color="red", alpha=0.5) +
    theme_bw() +
    theme(
      plot.title = element_text(size=10, hjust = 0.5, face="bold.italic"),
      legend.position = "bottom",
      legend.direction = "horizontal"
    ) +
    guides(color="none")
  mfp_vs_abr_plot_weighted
  ggsave(paste0("images/images_", output_version,"/weighted_mfp_vs_abr_plot_gabon_rdt.png"), mfp_vs_abr_plot_weighted, width=4250, height=3000, units="px", dpi=450)
  
  mean_age_grouped_mfp_data_500_sims <- gabon_mfp_age_grouped_data_500_sims %>% 
    group_by(ABR, age_groups, Ke) %>%
    summarise(
      mf_prev = mean(mf_prev) * 100,
      mf_q1 = quantile(mf_prev, probs=c(0.025)) * 100,
      mf_q3 = quantile(mf_prev, probs=c(0.975)) * 100,
      .groups="drop"
    ) %>%
    mutate(
      abr_ke = paste(ABR, Ke, sep="_"),
      mf_prev = ifelse(age_groups == 0, 0, mf_prev),
      mf_q1 = ifelse(age_groups == 0, 0, mf_q1),
      mf_q3 = ifelse(age_groups == 0, 0, mf_q3)
    ) %>%
    filter(
      abr_ke %in% (mean_weighted_mfp_data %>% filter(within_bounds) %>% select(abr_ke) %>% .$abr_ke)
    )
  
  test_mse_plot <- ggplot() + 
    geom_point(data=summarize_gabon_multicountry_data, aes(x=age_groups, y=mf_prev*100, color="Observed Data")) +
    geom_errorbar(data=summarize_gabon_multicountry_data, aes(x=age_groups, ymin=mf_wilson_lb*100, ymax=mf_wilson_ub*100, color="Observed Data"), width=2.5, alpha=0.5) +
    geom_line(data=mean_age_grouped_mfp_data_500_sims, aes(x=age_groups, y=mf_prev, color=abr_ke)) +
    geom_label_repel(data=mean_age_grouped_mfp_data_500_sims %>% filter(age_groups > 75), aes(x=age_groups, y=mf_prev + 1, label=abr_ke), hjust=1) +
    xlab("Age (years)") +
    ylab("Microfilarial Prevalence (%)") +
    scale_x_continuous(breaks=seq(0, 80, 10), limits=c(0, 90)) +
    scale_color_manual("ABR/kE", values=c("red", "red", "red", "red", "lightblue", "lightblue", "lightblue", "black"))
  test_mse_plot
  ggsave(paste0("images/images_", output_version,"/test_mse_plots_gabon_rdt.png"), test_mse_plot, width=4250, height=3000, units="px", dpi=450)
  
  calcResidualsMFP(summarize_gabon_multicountry_data, mean_age_grouped_mfp_data_500_sims %>% rename(mf_prev_proj = mf_prev))
  
  mfpDieOut <- readRDS("data/gabon_agg_data_rdt_mfp_test_200_years/rdt_gabon_mfp_data_500_sims.RDS")$mf_prev_df %>% 
    as.data.frame() %>%
    group_by(ABR, Ke, run_num) %>%
    mutate(time = row_number())
  
  mfpDieOut %>% group_by(time, ABR, Ke) %>% summarise(mf_prev = mean(mf_prev), .groups="drop") %>% 
    ggplot() + geom_line(aes(x=time, y=mf_prev, color=factor(Ke), linetype=factor(ABR)))
  mfpDieOut %>%
    filter(time > 80) %>%
    group_by(ABR, Ke, run_num) %>%
    summarise(
      has_died_out = any(mf_prev <= 0),
      .groups="drop"
    ) %>% 
    group_by(ABR, Ke) %>%
    summarise(
      prop_died_out = mean(has_died_out),
      .groups="drop"
    ) %>% View()
  
  
  rm(gabon_mfp_age_grouped_data_100_sims)
  rm(gabon_mfp_age_grouped_data_500_sims)
  rm(weighted_mfp_data)
  rm(mfpDieOut)
}
```

#### ELISA Simulations

##### New Runs Pre-Aggregated
```{r}
folder = "gabon_agg_data_rdt_4400_pop_updated_seroreversion_worm_revert/"#"gabon_agg_data_rdt_4400_pop/"#"gabon_agg_data_rdt_orig/"
gabon_100_mount_agg <- readRDS(paste0("data/", folder, "rdt_gabon_100_mount_data.RDS"))
gabon_sero_agg <- readRDS(paste0("data/", folder, "rdt_gabon_seroreversion_data.RDS"))
gabon_mfp_data <- readRDS(paste0("data/", folder, "rdt_gabon_mfp_data.RDS"))
# 100% of population mount antibody response k3
summarizeSimulatedGabon_elisa_100_mount_k3 <- gabon_100_mount_agg$allOutputs %>% filter(Ke == 0.3) %>% filter(run_num <= 4500)
simulation_summary_elisa_100_mount_k3 <- summarizeSimulationData(summarizeSimulatedGabon_elisa_100_mount_k3, groupBySex=FALSE)

# 100% of population mount antibody response k2
summarizeSimulatedGabon_elisa_100_mount <-  gabon_100_mount_agg$allOutputs %>% filter(Ke == 0.2) %>% filter(run_num <= 1500)
simulation_summary_elisa_100_mount <- summarizeSimulationData(summarizeSimulatedGabon_elisa_100_mount, groupBySex=FALSE)

# serorevert on trigger k2
summarizeSimulatedGabon_elisa_sero_trigger <- gabon_sero_agg$allOutputs %>% filter(Ke == 0.2 & sero_type == "absence_of_trigger")
simulation_summary_elisa_sero_trigger <- summarizeSimulationData(summarizeSimulatedGabon_elisa_sero_trigger, groupBySex=FALSE)

# serorevert with no infection k2
summarizeSimulatedGabon_elisa_sero_no_inf <- gabon_sero_agg$allOutputs %>% filter(Ke == 0.2 & sero_type == "no_infection")
simulation_summary_elisa_sero_no_inf <- summarizeSimulationData(summarizeSimulatedGabon_elisa_sero_no_inf, groupBySex=FALSE)

# serorevert on trigger k3
summarizeSimulatedGabon_elisa_sero_trigger_k3 <- gabon_sero_agg$allOutputs %>% filter(Ke == 0.3 & sero_type == "absence_of_trigger")
simulation_summary_elisa_sero_trigger_k3 <- summarizeSimulationData(summarizeSimulatedGabon_elisa_sero_trigger_k3, groupBySex=FALSE)

# serorevert with no infection k3
summarizeSimulatedGabon_elisa_sero_no_inf_k3 <- gabon_sero_agg$allOutputs %>% filter(Ke == 0.3 & sero_type == "no_infection")
simulation_summary_elisa_sero_no_inf_k3 <- summarizeSimulationData(summarizeSimulatedGabon_elisa_sero_no_inf_k3, groupBySex=FALSE)

gabon_mfp_data_df <- gabon_mfp_data$mf_prev_df %>% as.data.frame()
#gabon_mfp_data_df %>% group_by(ABR, Ke) %>% summarize(mean_mfp = mean(mf_prev)) %>% ungroup() %>% View()

rm(gabon_100_mount_agg)
rm(gabon_sero_agg)
rm(gabon_mfp_data)
```

```{r}
gabon_sero_trend <- as.data.frame(readRDS(paste0("data/", folder, "rdt_gabon_ov16_trends.RDS"))$ov16_trend_df) %>% group_by(Ke, run_num) %>% mutate(time = (row_number()/2)) %>% ungroup()

gabon_mfp_trend <- as.data.frame(readRDS(paste0("data/", folder, "rdt_gabon_mfp_data.RDS"))$mf_prev_df) %>% group_by(Ke, run_num) %>% mutate(time = row_number()) %>% ungroup()

ggplot() + geom_line(
  data=gabon_mfp_trend %>% group_by(time, Ke) %>% summarize(prev=mean(mf_prev), .groups="drop"),
  aes(x=time, y=prev*100, color="mfp", linetype=factor(Ke))) + 
  geom_line(
    data=gabon_sero_trend %>% group_by(time, Ke) %>% summarize(prev=mean(ov16_vals), .groups="drop"),
    aes(x=time, y=prev*100, color="ov16", linetype=factor(Ke))
  ) +
  xlim(0, 200) +
  scale_y_continuous(limits = c(0, 30), breaks=c(seq(0, 30, 5)))
```

## Sens/Spec

### Adjusting Simulation Data
Sensitivity and Specificity data for ELISA pulled from https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6169192/ 

#### New Runs
```{r summarize_data, timeit=TRUE}

elisa_sens_spec_vec_list <- list(c(0.40, 0.99), c(0.50, 0.99), c(0.60, 0.99),
                                 c(0.40, 0.97), c(0.50, 0.97), c(0.60, 0.97),
                                 c(0.40, 0.94), c(0.50, 0.94), c(0.60, 0.94))

base_k3_list <- list()
base_k2_list <- list()
sero_trigger_k3_list <- list()
sero_trigger_k2_list <- list()
sero_no_inf_k3_list <- list()
sero_no_inf_k2_list <- list()

for(elisa_sens_spec_vec in elisa_sens_spec_vec_list) {
  
  sens_spec_val <- paste(elisa_sens_spec_vec, collapse="_")
  simulation_summary_sens_spec_elisa_100_mount_k3 <- summarizeSimulationData(summarizeSimulatedGabon_elisa_100_mount_k3, elisa_sens_spec_vec, groupBySex=FALSE)
  base_k3_list[[sens_spec_val]] <- simulation_summary_sens_spec_elisa_100_mount_k3
  
  simulation_summary_sens_spec_elisa_100_mount <- summarizeSimulationData(summarizeSimulatedGabon_elisa_100_mount, elisa_sens_spec_vec, groupBySex=FALSE)
  base_k2_list[[sens_spec_val]] <- simulation_summary_sens_spec_elisa_100_mount
  
  simulation_summary_sens_spec_elisa_sero_trigger <- summarizeSimulationData(summarizeSimulatedGabon_elisa_sero_trigger, elisa_sens_spec_vec, groupBySex=FALSE)
  sero_trigger_k2_list[[sens_spec_val]] <- simulation_summary_sens_spec_elisa_sero_trigger
  
  simulation_summary_sens_spec_elisa_sero_no_inf <- summarizeSimulationData(summarizeSimulatedGabon_elisa_sero_no_inf, elisa_sens_spec_vec, groupBySex=FALSE)
  sero_no_inf_k2_list[[sens_spec_val]] <- simulation_summary_sens_spec_elisa_sero_no_inf
  
  simulation_summary_sens_spec_elisa_sero_trigger_k3 <- summarizeSimulationData(summarizeSimulatedGabon_elisa_sero_trigger_k3, elisa_sens_spec_vec, groupBySex=FALSE)
    sero_trigger_k3_list[[sens_spec_val]] <- simulation_summary_sens_spec_elisa_sero_trigger_k3
    
  simulation_summary_sens_spec_elisa_sero_no_inf_k3 <- summarizeSimulationData(summarizeSimulatedGabon_elisa_sero_no_inf_k3, elisa_sens_spec_vec, groupBySex=FALSE)
  sero_no_inf_k3_list[[sens_spec_val]] <- simulation_summary_sens_spec_elisa_sero_no_inf_k3
}

# if(simulateRDT) {
  #rdt_sens_spec_vec <- as.vector(unlist(gabon_rdt_sens_spec))
#  sex_split_simulation_summary_sens_spec_rdt <- summarizeSimulationData(summarizeSimulatedGabon_rdt, gabon_rdt_sens_spec, sensAgeGroup=sensAgeGroup)

#  simulation_summary_sens_spec_rdt <- summarizeSimulationData(summarizeSimulatedGabon_rdt, gabon_rdt_sens_spec, groupBySex=FALSE, sensAgeGroup=sensAgeGroup)

#  sex_split_simulation_summary_sens_spec_rdt_k2 <- summarizeSimulationData(summarizeSimulatedGabon_rdt_k2, gabon_rdt_sens_spec, sensAgeGroup=sensAgeGroup)

#  simulation_summary_sens_spec_rdt_k2 <- summarizeSimulationData(summarizeSimulatedGabon_rdt_k2, gabon_rdt_sens_spec, groupBySex=FALSE, sensAgeGroup=sensAgeGroup)
#}
```


## Plots

### MFP Plot Agg
```{r}
create_mfp_graph <- function(actual_data, projection_data, kE) {
  mfp_plot <- ggplot() + geom_point(data=actual_data %>% filter(age_groups != 0.0), aes(x=age_groups, y=mf_prev*100, color="Observed Data")) +
    geom_errorbar(data=actual_data %>% filter(age_groups != 0.0), aes(x=age_groups, ymin=mf_wilson_lb*100, ymax=mf_wilson_ub*100), width=2.5, alpha=0.5) + 
    geom_line(data=projection_data, aes(x=age_groups, y=mf_prev*100, color="Simulation kE = 0.3")) +
    geom_ribbon(data=projection_data, aes(x=age_groups, ymin=mf_q1*100, ymax=mf_q3*100), color="black", fill="black", linetype="dashed", alpha=0.2) +
    scale_color_manual("Type", values=c("black", "black")) +
    xlab("Age (years)") +
    ylab("Microfilarial prevalence (%)") +
    scale_x_continuous(breaks=seq(0, 80, 10)) +
    scale_y_continuous(breaks=seq(0, 20, 5), limits=c(0, 20.25)) +
    theme_bw() +
    theme(
      panel.grid.minor.x = element_blank()
    ) +
    guides(color="none")
  print(mfp_plot)
  ggsave(paste0("images/images_", output_version,"/gabon_rdt_mfp_graph_new_quartiles_", kE, ".png"),mfp_plot, width=4250, height=3000, units="px", dpi=450)
}

create_mfp_graph(summarize_gabon_multicountry_data, base_k3_list[[1]], "k3")
create_mfp_graph(summarize_gabon_multicountry_data, base_k2_list[[1]], "k2")

# Get overall MFP
summarizeSimulatedGabon_elisa_100_mount %>% filter(age >= 5) %>% group_by(run_num, ABR, Ke) %>% summarize(num_pos = sum(mf_prev), total=n(), mf_prev=mean(mf_prev), .groups="drop") %>% group_by(ABR, Ke) %>% summarize(q1=quantile(mf_prev, c(0.025)), q3=quantile(mf_prev, c(0.975)), mf_prev = mean(mf_prev), lb=wilson.ci(mean(num_pos), mean(total))[1], ub=wilson.ci(mean(num_pos), mean(total))[2],  .groups="drop") %>% View()

summarizeSimulatedGabon_elisa_100_mount_k3 %>% filter(age >= 5) %>% group_by(run_num, ABR, Ke) %>% summarize(num_pos = sum(mf_prev), total=n(), mf_prev=mean(mf_prev), .groups="drop") %>% group_by(ABR, Ke) %>% summarize(mf_prev = mean(mf_prev), lb=wilson.ci(mean(num_pos), mean(total))[1], ub=wilson.ci(mean(num_pos), mean(total))[2], .groups="drop")

custom_calc_resid_mfp(summarize_gabon_multicountry_data, summarizeSimulatedGabon_elisa_100_mount %>% mutate(abr_ke="76_0.2") %>% distinct() %>% data_manip_resid_mfp())

custom_calc_resid_mfp(summarize_gabon_multicountry_data, summarizeSimulatedGabon_elisa_100_mount_k3 %>% mutate(abr_ke="179_0.3") %>% distinct() %>% data_manip_resid_mfp())
```

### Make Adjusted Plot
```{r}
make_old_graphs = FALSE
if (make_old_graphs) {
  make_adjusted_plot <- function(df1, df2, compValLabel, compVal1, compVal2, df3, label="a)", desc="") {
  
  
  df2$Hypothesis <- factor(df2$Hypothesis, levels = c("L3 exposure", "L4-L5 moult", "Any worm", "Any Adult worm", "Mating worm pair", "Mating worm pair with any mf", "Mating worm pair with detectable mf"), ordered=TRUE)
  #color_vals <- c("L3 exposure"="green", "L4-L5 moult"="blue", "Any worm"="red", "Mating worm pair"="red", "Mating worm pair with any mf"="green", "Mating worm pair with detectable mf"="blue")
   color_vals <- c("Actual Data"="black", "Any worm"="blue", "Any Adult worm"="blue", "L3 exposure"="purple", "L4-L5 moult"="#6366f2", "Mating worm pair"="brown", "Mating worm pair with any mf"="red", "Mating worm pair with detectable mf"="orange")
  df3$Hypothesis <- factor(df3$Hypothesis, levels = c("L3 exposure", "L4-L5 moult", "Any worm", "Mating worm pair", "Mating worm pair with any mf", "Mating worm pair with detectable mf"), ordered=TRUE)
  
  plotLineTypes <- c("L3 exposure"="dashed", "L4-L5 moult"="dashed", "Any worm"="dashed", "Any Adult worm"="dashed", "Mating worm pair"="dotted", "Mating worm pair with any mf"="dotted", "Mating worm pair with detectable mf"="dotted")
  
  plotLineTypes <- c("L3 exposure"="dashed", "L4-L5 moult"="dashed", "Any worm"="dashed", "Any Adult worm"="dashed", "Mating worm pair"="dashed", "Mating worm pair with any mf"="dashed", "Mating worm pair with detectable mf"="dashed")
  
  plot <- ggplot() + geom_point(aes(x=age_groups, y=ov16_prev_rdt*100), alpha=0.5, color="black", size=0.5, data=df1) +
    geom_errorbar(aes(x=age_groups, ymin=(ov16_wilson_lb*100), ymax=(ov16_wilson_ub*100)), width=2.5, alpha=0.5, colour="black", data=df1) +
    
    geom_line(aes(x=age_groups, y=ov16_prev*100, color=Hypothesis, linetype=Hypothesis, alpha=1), linewidth=1.1, data=df2) +
    
    geom_line(aes(x=age_groups, y=ov16_prev*100, color=Hypothesis, linetype=Hypothesis, alpha=0.5), linewidth=1.1, data=df3) +
    
    scale_color_manual(name="Hypotheses", values=color_vals) +
    scale_linetype_manual(name="Hypotheses", values=plotLineTypes) +
    theme_bw() +
    ggtitle(paste(label))+#, "Gabon Seroprevalence Projections", desc)) +
    xlab("Age (years)") +
    ylab("Ov16 Seroprevalence (%)") +
    scale_alpha(compValLabel, labels=c(compVal2, compVal1), breaks=c(0.5, 0.9), range=c(0.3, 1))
  return(plot)
}

for (elisa_sens_spec_vec in elisa_sens_spec_vec_list) {
  sens_spec_val <- paste(elisa_sens_spec_vec, collapse="_")
  adjust_comp_100_mount_k2_1 <- make_adjusted_plot(summarize_gabon_multicountry_data, simulation_summary_elisa_100_mount %>% filterHypotheses(), "Diagnostic Adjustment", "No", "Yes", base_k2_list[[sens_spec_val]] %>% filterHypotheses()) + ylim(0,51)
  
  adjust_comp_100_mount_k2_2 <- make_adjusted_plot(summarize_gabon_multicountry_data, base_k2_list[[sens_spec_val]] %>% filterHypotheses(), "Diagnostic Adjustment", "No", "Yes", base_k2_list[[sens_spec_val]] %>% filterHypotheses(), label="") + ylim(0,25) + theme(legend.direction = "horizontal", legend.position = "bottom") + guides(alpha="none")
  
  #ggsave("images/gabon_just_adjusted_new_paper.png",adjust_comp_100_mount_k2_2, width=4250, height=3000, units="px", dpi=450)
  
  arranged_graph <- ((adjust_comp_100_mount_k2_1 + theme(legend.direction = "horizontal") + guides(alpha="none")) | (adjust_comp_100_mount_k2_2 + theme(legend.direction = "horizontal", axis.title.y=element_blank()) +  guides(alpha="none") + ggtitle("b)"))) + plot_layout(guides = "collect") + plot_annotation(
    theme = theme(legend.position = "bottom",
                  legend.direction = "horizontal")
  )
  #ggsave("images/gabon_adjust_comp_new_paper.png",arranged_graph, width=8500, height=6000, units="px", dpi=900)
  
  trig_sero_k2_1 <- make_adjusted_plot(summarize_gabon_multicountry_data, sero_trigger_k2_list[[sens_spec_val]] %>% filterHypotheses(), "Seroreversion", "Yes", "No", sero_trigger_k2_list[[sens_spec_val]] %>% filterHypotheses(), "b)", "w/ Seroreversion")
  
  inf_sero_k2_1 <- make_adjusted_plot(summarize_gabon_multicountry_data, sero_no_inf_k2_list[[sens_spec_val]] %>% filterHypotheses(), "Seroreversion", "Yes", "No", sero_no_inf_k2_list[[sens_spec_val]] %>% filterHypotheses(), "c)", "w/ Seroreversion")
  
  arranged_seroreversion_graph <- ((adjust_comp_100_mount_k2_2 + ggtitle("a)") + ylim(0, 25) + theme(legend.direction = "horizontal") + guides(alpha="none")) | (trig_sero_k2_1 + ylim(0, 25) + theme(legend.direction = "horizontal", axis.title.y=element_blank()) + guides(alpha="none", color="none", linetype="none")) | (inf_sero_k2_1 + ylim(0, 25) + theme(legend.direction = "horizontal", axis.title.y=element_blank()) + guides(alpha="none", color="none", linetype="none"))) + plot_layout(guides = "collect") + plot_annotation(
    theme = theme(legend.position = "bottom",
                  legend.direction = "horizontal")
  )
  print(arranged_seroreversion_graph)
  #ggsave(paste0("images/gabon_rdt_k2_sero_mount_fig_paper", sens_spec_val,".png"), arranged_seroreversion_graph, width=8250, height = 4000, units="px", dpi=900)
  #ggsave("images/gabon_k2_sero_mount_fig_paper.png", arranged_seroreversion_graph, width=8250, height = 4000, units="px", dpi=900)
  
  #make_adjusted_plot(summarize_gabon_multicountry_data, simulation_summary_sens_spec_elisa_100_mount, kE, "0.2", "0.3", simulation_summary_sens_spec_elisa_100_mount_k3)
}
}
```

### Adjusted-Plot diff sens/spec
```{r}
filterHypotheses <- function(data) {
  actual_hyps <- c("Any worm", "L3 exposure", "L4-L5 moult", "Mating worm pair with any mf")
  data <- data %>% filter(Hypothesis %in% actual_hyps) %>% mutate(
    Hypothesis = ifelse(Hypothesis == "Any worm", "Any Adult worm", Hypothesis)
  )
}

make_adjusted_plot_sens_spec <- function(df1, df2, label="a)", desc="", combine_pre_patent=FALSE, combine_pre_adult_worm=FALSE, row_pre_patent=FALSE, sero_val="i", ylim=45) {
  df1 <- df1 %>% filter(age_groups != 0.0)
  tmp_df_holder <- list()
  facet_sens_spec = FALSE
  if(typeof(df2) == "list") {
    facet_sens_spec = TRUE
    for(val in names(df2)) {
      sens_spec_vals = as.numeric(strsplit(val, "_")[[1]])
      tmp <- df2[[val]] %>% mutate(sens = paste0(round(sens_spec_vals[1] * 100), "%"), spec = paste0(round(sens_spec_vals[2] * 100), "%")) %>% filterHypotheses()
      if (combine_pre_patent) {
        tmp <- tmp %>% mutate(
          Hypothesis = ifelse(Hypothesis == "Mating worm pair with any mf", paste0("H4", sero_val), paste0("H1", sero_val, "-3", sero_val))
          ) %>% 
          group_by(age_groups, Hypothesis, sens, spec) %>% 
          summarise(across(where(is.numeric), mean), .groups="drop")
      }
      if (combine_pre_adult_worm) {
        tmp <- tmp %>% mutate(
          Hypothesis = ifelse(
            Hypothesis == "Mating worm pair with any mf", 
            paste0("H4", sero_val), 
            ifelse(
              Hypothesis == "Any Adult worm",
              paste0("H3", sero_val),
              paste0("H1", sero_val, "-2", sero_val)
            )
          )) %>% 
          group_by(age_groups, Hypothesis, sens, spec) %>% 
          summarise(across(where(is.numeric), mean), .groups="drop")
      }
      if(length(tmp_df_holder) == 0) {
        tmp_df_holder <- tmp
      } else {
        tmp_df_holder <- rbind(tmp_df_holder, tmp)
      }
    }
  }
  df2 = tmp_df_holder %>% mutate(
    ov16_upper = ifelse(
      ov16_upper*100 > ylim,
      ylim/100,
      ov16_upper
    ),
    ov16_upper = ifelse(
      age_groups == 0,
      ov16_prev,
      ov16_upper
    ),
    ov16_lower = ifelse(
      age_groups == 0,
      ov16_prev,
      ov16_lower
    )
  )

  df2$Hypothesis <- factor(df2$Hypothesis, levels = c("L3 exposure", "L4-L5 moult", "Any worm", "Any Adult worm", "Pre-Patent Infection", "Mating worm pair", "Mating worm pair with any mf", "Mating worm pair with detectable mf", "H1-3", "H4", "H1i-3i", "H4i", "H1ii-2ii", "H3ii", "H1ii-3ii", "H4ii", "H1iii-3iii", "H4iii"), ordered=TRUE)

   color_vals <- c("Actual Data"="black", "Any worm"="blue", "Any Adult worm"="blue", "L3 exposure"="purple", "L4-L5 moult"="#6366f2", "Pre-Patent Infection"="blue", "Mating worm pair"="brown", "Mating worm pair with any mf"="red", "Mating worm pair with detectable mf"="orange", "H1-3"="blue", "H4"="red", "H1-3i"="blue", "H4i"="red", "H1-3ii"="blue", "H4ii"="red", "H1-3iii"="blue", "H4iii"="red")
   
    color_vals <- c("Actual Data"="black", "Any worm"="blue", "Any Adult worm"="blue", "L3 exposure"="purple", "L4-L5 moult"="darkgreen", "Pre-Patent Infection"="blue", "Mating worm pair"="brown", "Mating worm pair with any mf"="red", "Mating worm pair with detectable mf"="orange", "H1-3"="blue", "H4"="red", "H1i-3i"="blue", "H4i"="red", "H1ii-3ii"="blue", "H4ii"="red", "H1iii-3iii"="blue", "H4iii"="red", "H1ii-2ii"="purple", "H3ii" ="blue")
   
  plotLineTypes <- c("L3 exposure"="dashed", "L4-L5 moult"="dashed", "Any worm"="dashed", "Any Adult worm"="dashed", "Pre-Patent Infection"="solid", "Mating worm pair"="dashed", "Mating worm pair with any mf"="dashed", "Mating worm pair with detectable mf"="dashed")
  
  if(combine_pre_patent | row_pre_patent) {
      plotLineTypes <- c("L3 exposure"="solid", "L4-L5 moult"="solid", "Any worm"="solid", "Any Adult worm"="solid", "Pre-Patent Infection"="solid", "Mating worm pair"="solid", "Mating worm pair with any mf"="solid", "Mating worm pair with detectable mf"="solid", "H1-3"="solid", "H4"="solid", "H1i-3i"="solid", "H4i"="solid", "H1ii-3ii"="solid", "H4ii"="solid", "H1iii-3iii"="solid", "H4iii"="solid")
  }
  if (combine_pre_adult_worm) {
    plotLineTypes <- c("L3 exposure"="solid", "L4-L5 moult"="solid", "Any worm"="solid", "Any Adult worm"="solid", "Pre-Patent Infection"="solid", "Mating worm pair"="solid", "Mating worm pair with any mf"="solid", "Mating worm pair with detectable mf"="solid", "H1-3"="solid", "H4"="solid", "H1i-3i"="solid", "H4i"="solid", "H1ii-3ii"="solid", "H4ii"="solid", "H1ii-2ii"="solid", "H3ii" ="solid",  "H1iii-3iii"="solid", "H4iii"="solid")
  }
  
  plot <- ggplot() + geom_point(aes(x=age_groups, y=ov16_prev_rdt*100), alpha=0.5, color="black", size=0.5, data=df1) +
    geom_errorbar(aes(x=age_groups, ymin=(ov16_wilson_lb*100), ymax=(ov16_wilson_ub*100)), width=2.5, alpha=0.5, colour="black", data=df1)
  
  if(row_pre_patent) {
    pre_patent_hyp <- df2 %>% filter(Hypothesis != "Mating worm pair with any mf") %>% mutate(
      pre_patent_hyp = Hypothesis
    )
    patent_hyp <- list()
    for(pre_patent_hyp_val in unique(pre_patent_hyp$Hypothesis)) {
      if(length(patent_hyp) == 0) {
        patent_hyp <- df2 %>% filter(Hypothesis == "Mating worm pair with any mf") %>% mutate(pre_patent_hyp = pre_patent_hyp_val)
      } else {
        patent_hyp <- rbind(patent_hyp, df2 %>% filter(Hypothesis == "Mating worm pair with any mf") %>% mutate(pre_patent_hyp = pre_patent_hyp_val))
      }
    }
    df2 <- rbind(pre_patent_hyp, patent_hyp)
    list_of_plots <- list()
    for(spec_val in unique(df2$spec)) {
      list_of_plots[[as.character(spec_val)]] <- plot +
        geom_line(aes(x=age_groups, y=ov16_prev*100, color=Hypothesis, linetype=Hypothesis, alpha=1), linewidth=0.6, data=df2 %>% filter(spec == spec_val)) +
        scale_color_manual(name="Hypotheses", values=color_vals) +
        scale_linetype_manual(name="Hypotheses", values=plotLineTypes) +
        theme_bw() +
        #ggtitle(paste(label)) +
        xlab("Age (years)") +
        ylab("Ov16 Seroprevalence (%)") +
        guides(alpha="none", color=guide_legend(nrow=2)) +
        theme(
          legend.position = "bottom",
          legend.direction = "horizontal"
          ) +
        facet_grid(sens ~ pre_patent_hyp)
    }
    return(list_of_plots)
  }
  plot <- plot + geom_line(aes(x=age_groups, y=ov16_prev*100, color=Hypothesis, linetype=Hypothesis, alpha=1), linewidth=0.6, data=df2) +
    geom_ribbon(aes(x=age_groups, ymin=ov16_lower*100, ymax=ov16_upper*100, fill=Hypothesis), color=NA, alpha=0.1, data=df2) +
    scale_color_manual(name="Hypotheses", values=color_vals) +
    scale_fill_manual(name="Hypotheses", values=color_vals) +
    scale_linetype_manual(name="Hypotheses", values=plotLineTypes) +
    theme_bw() +
    #ggtitle(paste(label)) +
    xlab("Age (years)") +
    ylab("Anti-Ov16 seroprevalence (%)") +
    scale_y_continuous(
      limits=c(0, ylim), 
      breaks=seq(0, 40, 10),
      sec.axis = sec_axis(~ . , name = "Sensitivity", breaks = NULL, labels = NULL)
    ) +
    guides(alpha="none", color=guide_legend(nrow=1)) +
    theme(
      legend.position = "bottom",
      legend.direction = "horizontal",
      plot.title = element_text(size=10, hjust = 0.5),
      axis.title.y = element_text(size=10),
      title = element_text(size=10),
      legend.text = element_text(size=6),
      legend.title = element_text(size=8),
      legend.key.size = unit(0.8, 'lines'),
      axis.text.y = element_text(size=6),
      axis.text.x = element_text(size=6),
      strip.placement = "outside",
      panel.grid.minor = element_blank(),
      axis.line.x = element_line(color = "black"),
      axis.line.y = element_line(color = "black"),
      strip.text.y = element_text(angle=0),
      axis.line.y.right = element_blank()
    )
  if (facet_sens_spec) {
    plot <- plot + facet_grid(sens ~ spec) +
      ggtitle("Specificity")
  }
  return(plot)
}

#sens_spec_all_hyp <- make_adjusted_plot_sens_spec(summarize_gabon_multicountry_data, base_k3_list, ylim=42)
#sens_spec_all_hyp
#ggsave(paste0("images/images_", output_version,"/gabon_rdt_sens_spec_k3.png"), sens_spec_all_hyp, units="in", height=4, width=5.5, dpi=300)

### ke = 0.3
sens_spec_combine_pre_patent <- make_adjusted_plot_sens_spec(summarize_gabon_multicountry_data, base_k3_list, combine_pre_patent=TRUE, sero_val = "i", ylim=42)
sens_spec_combine_pre_patent
ggsave(paste0("images/images_", output_version,"/gabon_rdt_sens_spec_pre_patent_combined_k3.png"), sens_spec_combine_pre_patent, units="in", height=4, width=5.5, dpi=300)

sero_no_inf_sens_spec_all_hyp <- make_adjusted_plot_sens_spec(summarize_gabon_multicountry_data, sero_no_inf_k3_list, combine_pre_patent = TRUE, sero_val = "iii", ylim=42)
sero_no_inf_sens_spec_all_hyp
ggsave(paste0("images/images_", output_version,"/gabon_rdt_sens_spec_pre_patent_combined_sero_no_inf_k3.png"), sero_no_inf_sens_spec_all_hyp, units="in", height=4, width=5.5, dpi=300)

sero_trigger_sens_spec_all_hyp <- make_adjusted_plot_sens_spec(summarize_gabon_multicountry_data, sero_trigger_k3_list, combine_pre_patent = FALSE, combine_pre_adult_worm = TRUE, sero_val = "ii", ylim=42)
sero_trigger_sens_spec_all_hyp
ggsave(paste0("images/images_", output_version,"/gabon_rdt_sens_spec_pre_patent_not_combined_sero_trigger_k3.png"), sero_trigger_sens_spec_all_hyp, units="in", height=4, width=5.5, dpi=300)

#sens_spec_row_pre_patent <- make_adjusted_plot_sens_spec(summarize_gabon_multicountry_data, base_k3_list, row_pre_patent=TRUE)
#for (spec in names(sens_spec_row_pre_patent)) {
#  ggsave(paste0("images/images_", output_version,"/gabon_rdt_sens_", as.character(spec), "_spec_col_pre_patent_k3.png"), sens_spec_row_pre_patent[[spec]], units="in", height=4, width=5.5, dpi=300)
#}

### ke = 0.2

sens_spec_combine_pre_patent <- make_adjusted_plot_sens_spec(summarize_gabon_multicountry_data, base_k2_list, combine_pre_patent=TRUE, sero_val = "i", ylim=42)
sens_spec_combine_pre_patent
ggsave(paste0("images/images_", output_version,"/gabon_rdt_sens_spec_pre_patent_combined_k2.png"), sens_spec_combine_pre_patent, units="in", height=4, width=5.5, dpi=300)

sero_no_inf_sens_spec_all_hyp <- make_adjusted_plot_sens_spec(summarize_gabon_multicountry_data, sero_no_inf_k2_list, combine_pre_patent = TRUE, sero_val = "iii", ylim=42)
sero_no_inf_sens_spec_all_hyp
ggsave(paste0("images/images_", output_version,"/gabon_rdt_sens_spec_pre_patent_combined_sero_no_inf_k2.png"), sero_no_inf_sens_spec_all_hyp, units="in", height=4, width=5.5, dpi=300)

sero_trigger_sens_spec_all_hyp <- make_adjusted_plot_sens_spec(summarize_gabon_multicountry_data, sero_trigger_k2_list, combine_pre_patent = FALSE, combine_pre_adult_worm = TRUE, sero_val = "ii", ylim=42)
sero_trigger_sens_spec_all_hyp
ggsave(paste0("images/images_", output_version,"/gabon_rdt_sens_spec_pre_patent_not_combined_sero_trigger_k2.png"), sero_trigger_sens_spec_all_hyp, units="in", height=4, width=5.5, dpi=300)
```

### Create Final Plots
```{r}

summarize_for_plots <- function(df, sero_val) {
  output_df <- list()
  for(val in names(df)) {
    sens_spec_vals = as.numeric(strsplit(val, "_")[[1]])
    tmp <- df[[val]] %>% mutate(sens = paste0(round(sens_spec_vals[1] * 100), "%"), spec = paste0(round(sens_spec_vals[2] * 100), "%")) %>% filterHypotheses()
    if (sero_val != "ii") {
      tmp <- tmp %>% mutate(
        Hypothesis = ifelse(Hypothesis == "Mating worm pair with any mf", paste0("H4", sero_val), paste0("H1", sero_val, "-3", sero_val))
        ) %>% 
        group_by(age_groups, Hypothesis, sens, spec) %>% 
        summarise(across(where(is.numeric), mean), .groups="drop")
    } else {
      tmp <- tmp %>% mutate(
        Hypothesis = ifelse(
          Hypothesis == "Mating worm pair with any mf", 
          paste0("H4", sero_val), 
          ifelse(
            Hypothesis == "Any Adult worm",
            paste0("H3", sero_val),
            paste0("H1", sero_val, "-2", sero_val)
          )
        )
      ) %>% 
      group_by(age_groups, Hypothesis, sens, spec) %>% 
      summarise(across(where(is.numeric), mean), .groups="drop")
    }
    tmp <- tmp %>% mutate(sens_spec = paste0(sens, ", ", spec))
    if(length(output_df) == 0) {
      output_df <- tmp
    } else {
      output_df <- rbind(output_df, tmp)
    }
  }
  return(output_df)
}
color_vals <- c("Actual Data"="black", "H1i-3i"="blue", "H4i"="red", "H1ii-3ii"="blue", "H4ii"="red", "H1iii-3iii"="blue", "H4iii"="red", "H1ii-2ii"="purple", "H3ii" ="blue")
df1 <- summarize_gabon_multicountry_data
df2 <- summarize_for_plots(base_k2_list, "i")
df3 <- summarize_for_plots(sero_trigger_k2_list, "ii")
df4 <- summarize_for_plots(sero_no_inf_k2_list, "iii")

all_sero_hyp = rbind(df2, df3, df4) %>%
  mutate(label_val = paste(Hypothesis, sens_spec, sep=" | "))

plot <-  ggplot() + geom_point(aes(x=age_groups, y=ov16_prev_rdt*100), alpha=0.5, color="black", size=0.5, data=df1 %>% filter(age_groups > 0)) +
    geom_errorbar(aes(x=age_groups, ymin=(ov16_wilson_lb*100), ymax=(ov16_wilson_ub*100)), width=2.5, alpha=0.5, colour="black", data=df1 %>% filter(age_groups > 0)) +
   geom_line(aes(x=age_groups, y=ov16_prev*100, color=Hypothesis), linewidth=0.6, data=all_sero_hyp %>% #, linetype=sens_spec
               filter(
                 (Hypothesis == "H4i" & sens == "40%" & spec == "99%") |
                   (Hypothesis == "H4iii" & sens == "50%" & spec == "99%") |
                   (Hypothesis == "H1iii-3iii" & sens == "40%" & spec == "99%") |
                   (Hypothesis == "H3ii" & sens == "40%" & spec == "99%")
                 )
             ) +
    geom_ribbon(aes(x=age_groups, ymin=ov16_lower*100, ymax=ov16_upper*100, fill=Hypothesis), color=NA, alpha=0.1, data=all_sero_hyp %>%
               filter(
                 (Hypothesis == "H4i" & sens == "40%" & spec == "99%") |
                   (Hypothesis == "H4iii" & sens == "50%" & spec == "99%") |
                   (Hypothesis == "H1iii-3iii" & sens == "40%" & spec == "99%") |
                   (Hypothesis == "H3ii" & sens == "40%" & spec == "99%")
                 )) +
  scale_color_manual(name="Hypotheses", values=color_vals) +
  scale_fill_manual(name="Hypotheses", values=color_vals) +
  # geom_label_repel(direction = "x", nudge_x = 1.5, nudge_y = 1, aes(x=age_groups, y=ov16_prev*100, label=label_val), data = all_sero_hyp %>%
  #              filter(
  #                (age_groups > 75) &
  #                (
  #                  (Hypothesis == "H4i" & sens == "40%" & spec == "99%") |
  #                  (Hypothesis == "H4iii" & sens == "50%" & spec == "99%") |
  #                  (Hypothesis == "H1iii-3iii" & sens == "40%" & spec == "99%") |
  #                  (Hypothesis == "H3ii" & sens == "40%" & spec == "99%")
  #                )
  #              )
  #            ) +
  theme_bw() +
  xlab("Age (years)") +
  ylab("Anti-Ov16 seroprevalence (%)") +
  guides(alpha="none", linetype="none", color=guide_legend(nrow=1)) +
  theme(
    legend.position = "bottom",
    legend.direction = "horizontal",
    plot.title = element_text(size=10, hjust = 0.5),
    axis.title.y = element_text(size=10),
    title = element_text(size=10),
    legend.text = element_text(size=6),
    legend.title = element_text(size=8),
    legend.key.size = unit(0.8, 'lines'),
    axis.text.y = element_text(size=6),
    axis.text.x = element_text(size=6),
    strip.placement = "outside",
    panel.grid.minor = element_blank(),
    axis.line.x = element_line(color = "black"),
    axis.line.y = element_line(color = "black"),
    strip.text.y = element_text(angle=0),
    axis.line.y.right = element_blank()
  )
plot

ggsave(paste0("images/images_", output_version,"/best_4_fitting_hyps_gabon_rdt.png"), plot, width=4250, height=3000, units="px", dpi=450)

plot_2 <-  ggplot() + geom_point(aes(x=age_groups, y=ov16_prev_rdt*100), alpha=0.5, color="black", size=0.5, data=df1 %>% filter(age_groups > 0)) +
    geom_errorbar(aes(x=age_groups, ymin=(ov16_wilson_lb*100), ymax=(ov16_wilson_ub*100)), width=2.5, alpha=0.5, colour="black", data=df1 %>% filter(age_groups > 0)) +
   geom_line(aes(x=age_groups, y=ov16_prev*100, color=Hypothesis, linetype=sens_spec), linewidth=0.6, data=all_sero_hyp %>%
               filter(
                 (Hypothesis == "H4i" & sens == "40%" & spec == "99%") |
                   (Hypothesis == "H4iii" & sens == "50%" & spec == "99%")
                 )
             ) +
    geom_ribbon(aes(x=age_groups, ymin=ov16_lower*100, ymax=ov16_upper*100, fill=Hypothesis), color=NA, alpha=0.1, data=all_sero_hyp %>%
               filter(
                 (Hypothesis == "H4i" & sens == "40%" & spec == "99%") |
                   (Hypothesis == "H4iii" & sens == "50%" & spec == "99%")
                 )) +
  geom_label_repel(size=3, direction = "x", nudge_x = 2, nudge_y = -1.1, aes(x=age_groups, y=ov16_prev*100, label=label_val), data = all_sero_hyp %>%
               filter(
                 (age_groups > 75) &
                 (
                   (Hypothesis == "H4i" & sens == "40%" & spec == "99%") |
                   (Hypothesis == "H4iii" & sens == "50%" & spec == "99%")
                 )
               )
             ) +
  scale_color_manual(name="Hypotheses", values=color_vals) +
  scale_fill_manual(name="Hypotheses", values=color_vals) +
  scale_linetype_manual("", values=c("50%, 99%"="dashed", "40%, 99%"="dotted")) +
  theme_bw() +
  xlab("Age (years)") +
  ylab("Anti-Ov16 seroprevalence (%)") +
  guides(alpha="none", linetype="none", color=guide_legend(nrow=1)) +
  theme(
    legend.position = "bottom",
    legend.direction = "horizontal",
    plot.title = element_text(size=10, hjust = 0.5),
    axis.title.y = element_text(size=10),
    title = element_text(size=10),
    legend.text = element_text(size=6),
    legend.title = element_text(size=8),
    legend.key.size = unit(0.8, 'lines'),
    axis.text.y = element_text(size=6),
    axis.text.x = element_text(size=6),
    strip.placement = "outside",
    panel.grid.minor = element_blank(),
    axis.line.x = element_line(color = "black"),
    axis.line.y = element_line(color = "black"),
    strip.text.y = element_text(angle=0),
    axis.line.y.right = element_blank()
  )
plot_2

ggsave(paste0("images/images_", output_version,"/best_2_fitting_hyps_gabon_rdt.png"), plot_2, width=4250, height=3000, units="px", dpi=450)


plot_3_all_sero_hyp <- all_sero_hyp %>%
  filter(
    ((sens == "40%" & spec == "99%")) |
     ((sens == "50%" & spec == "99%") & grepl("iii", Hypothesis))
  ) %>%
  mutate(
    sero_hyp = case_when(
      grepl("iii", Hypothesis) ~ "iii",
      grepl("ii", Hypothesis) ~ "ii",
      TRUE ~ "i"
    ),
    show_ribbon = case_when(
      sens == "40%" & spec == "99%" & Hypothesis == "H4i" ~ TRUE,
      sens == "40%" & spec == "99%" & Hypothesis == "H3ii" ~ TRUE,
      sens == "40%" & spec == "99%" & Hypothesis == "H1iii-3iii" ~ TRUE,
      sens == "50%" & spec == "99%" & Hypothesis == "H4iii" ~ TRUE,
      TRUE ~ FALSE
    ),
    alpha_val = case_when(
      sens == "40%" & spec == "99%" & Hypothesis == "H4i" ~ 1,
      sens == "40%" & spec == "99%" & Hypothesis == "H3ii" ~ 1,
      sens == "40%" & spec == "99%" & Hypothesis == "H1iii-3iii" ~ 1,
      sens == "50%" & spec == "99%" & Hypothesis == "H4iii" ~ 1,
      TRUE ~ 0.3
    )
  )

plot_3 <- ggplot() + geom_point(aes(x=age_groups, y=ov16_prev_rdt*100), alpha=0.5, color="black", size=0.5, data=df1 %>% filter(age_groups > 0)) +
    geom_errorbar(aes(x=age_groups, ymin=(ov16_wilson_lb*100), ymax=(ov16_wilson_ub*100)), width=2.5, alpha=0.5, colour="black", data=df1 %>% filter(age_groups > 0)) +
   geom_line(aes(x=age_groups, y=ov16_prev*100, color=Hypothesis, alpha=alpha_val), linewidth=0.6, data=plot_3_all_sero_hyp) +
    geom_ribbon(aes(x=age_groups, ymin=ov16_lower*100, ymax=ov16_upper*100, fill=Hypothesis), color=NA, alpha=0.1, data=plot_3_all_sero_hyp %>% filter(show_ribbon == TRUE)) +
  scale_color_manual(name="Hypotheses", values=color_vals) +
  scale_fill_manual(name="Hypotheses", values=color_vals) +
  scale_alpha_continuous(range = c(0.3, 1)) +
  theme_bw() +
  facet_wrap(sero_hyp~sens_spec) +
  xlab("Age (years)") +
  ylab("Anti-Ov16 seroprevalence (%)") +
  guides(alpha="none", linetype="none", color=guide_legend(nrow=1)) +
  theme(
    legend.position = "bottom",
    legend.direction = "horizontal",
    plot.title = element_text(size=10, hjust = 0.5),
    axis.title.y = element_text(size=10),
    title = element_text(size=10),
    legend.text = element_text(size=6),
    legend.title = element_text(size=8),
    legend.key.size = unit(0.8, 'lines'),
    axis.text.y = element_text(size=6),
    axis.text.x = element_text(size=6),
    strip.placement = "outside",
    panel.grid.minor = element_blank(),
    axis.line.x = element_line(color = "black"),
    axis.line.y = element_line(color = "black"),
    strip.text.y = element_text(angle=0),
    axis.line.y.right = element_blank()
  )
plot_3

ggsave(paste0("images/images_", output_version,"/best_4_fitting_hyps_gabon_rdt_with_comparisons.png"), plot_3, width=4250, height=3000, units="px", dpi=450)

plot_4_all_sero_hyp <- all_sero_hyp %>%
  filter(
    ((sens == "40%" & spec == "99%") & Hypothesis %in% c("H4i")) |#, "H1i-3i")) |
     ((sens == "50%" & spec == "99%") & grepl("H4iii", Hypothesis))
  ) %>%
  mutate(
    sero_hyp = case_when(
      grepl("iii", Hypothesis) ~ "H4iii",
      grepl("ii", Hypothesis) ~ "H4ii",
      TRUE ~ "H4i"
    ),
    show_ribbon = case_when(
      sens == "40%" & spec == "99%" & Hypothesis == "H4i" ~ TRUE,
      sens == "40%" & spec == "99%" & Hypothesis == "H3ii" ~ TRUE,
      sens == "40%" & spec == "99%" & Hypothesis == "H1iii-3iii" ~ TRUE,
      sens == "50%" & spec == "99%" & Hypothesis == "H4iii" ~ TRUE,
      TRUE ~ FALSE
    ),
    alpha_val = case_when(
      sens == "40%" & spec == "99%" & Hypothesis == "H4i" ~ 1,
      sens == "40%" & spec == "99%" & Hypothesis == "H3ii" ~ 1,
      sens == "40%" & spec == "99%" & Hypothesis == "H1iii-3iii" ~ 1,
      sens == "50%" & spec == "99%" & Hypothesis == "H4iii" ~ 1,
      TRUE ~ 0.3
    )
  )

plot_4 <- ggplot() + geom_point(aes(x=age_groups, y=ov16_prev_rdt*100), alpha=0.5, color="black", size=0.5, data=df1 %>% filter(age_groups > 0)) +
    geom_errorbar(aes(x=age_groups, ymin=(ov16_wilson_lb*100), ymax=(ov16_wilson_ub*100)), width=2.5, alpha=0.5, colour="black", data=df1 %>% filter(age_groups > 0)) +
   geom_line(aes(x=age_groups, y=ov16_prev*100, color=Hypothesis, alpha=alpha_val), linewidth=0.6, data=plot_4_all_sero_hyp) +
    geom_ribbon(aes(x=age_groups, ymin=ov16_lower*100, ymax=ov16_upper*100, fill=Hypothesis), color=NA, alpha=0.1, data=plot_4_all_sero_hyp %>% filter(show_ribbon == TRUE)) +
  scale_color_manual(name="Hypotheses", values=c("black", "black")) +
  scale_fill_manual(name="Hypotheses", values=c("black", "black")) +
  scale_alpha_continuous(range = c(0.3, 1)) +
  theme_bw() +
  facet_wrap(sero_hyp~sens_spec) +
  xlab("Age (years)") +
  ylab("Anti-Ov16 seroprevalence (%)") +
  guides(alpha="none", linetype="none", color="none", fill="none") + #guide_legend(nrow=1)) +
  theme(
    legend.position = "bottom",
    legend.direction = "horizontal",
    plot.title = element_text(size=10, hjust = 0.5),
    axis.title.y = element_text(size=10),
    title = element_text(size=10),
    legend.text = element_text(size=6),
    legend.title = element_text(size=8),
    legend.key.size = unit(0.8, 'lines'),
    axis.text.y = element_text(size=6),
    axis.text.x = element_text(size=6),
    strip.placement = "outside",
    panel.grid.minor = element_blank(),
    axis.line.x = element_line(color = "black"),
    axis.line.y = element_line(color = "black"),
    strip.text.y = element_text(angle=0),
    axis.line.y.right = element_blank()
  )
plot_4

ggsave(paste0("images/images_", output_version,"/best_2_fitting_hyps_gabon_rdt_without_comparisons.png"), plot_4, width=4250, height=3000, units="px", dpi=450)


library(lme4)

tmp <- summarizeSimulatedGabon_elisa_100_mount
tmp$probs <- runif(dim(tmp)[1])
sum_tmp <- tmp %>% group_by(run_num) %>% mutate(
    #H1i=calcSensSpecSeroPrev(ov16_pos_l3, 40, 99, probs),
    #H2i=calcSensSpecSeroPrev(ov16_pos_l4, 40, 99, probs),
    #H3i=calcSensSpecSeroPrev(ov16_pos, 40, 99, probs),
    H4i=calcSensSpecSeroPrev(ov16_pos_mating_any_mf, 40, 99, probs)
  ) %>% pivot_longer(
    cols=c(H4i), names_to="Hypothesis", values_to = "ov16_prev"
  ) %>% 
  select(run_num, Hypothesis, ov16_prev, age_groups)
tmp <- summarizeSimulatedGabon_elisa_sero_trigger
tmp$probs <- runif(dim(tmp)[1])
sum_tmp <- rbind(sum_tmp, tmp %>% group_by(run_num) %>% mutate(
      #H1ii=calcSensSpecSeroPrev(ov16_pos_l3, 40, 99, probs),
      #H2ii=calcSensSpecSeroPrev(ov16_pos_l4, 40, 99, probs),
      H3ii=calcSensSpecSeroPrev(ov16_pos, 40, 99, probs)
      #H4ii=calcSensSpecSeroPrev(ov16_pos_mating_any_mf, 40, 99, probs)
    ) %>% pivot_longer(
      cols=c(H3ii), names_to="Hypothesis", values_to = "ov16_prev"
    ) %>% 
    select(run_num, Hypothesis, ov16_prev, age_groups)
  )
tmp <- summarizeSimulatedGabon_elisa_sero_no_inf
tmp$probs <- runif(dim(tmp)[1])
sum_tmp <- rbind(sum_tmp, tmp %>% group_by(run_num) %>% mutate(
      #H1ii=calcSensSpecSeroPrev(ov16_pos_l3, 40, 99, probs),
      #H2ii=calcSensSpecSeroPrev(ov16_pos_l4, 40, 99, probs),
      #H3ii=calcSensSpecSeroPrev(ov16_pos, 40, 99, probs),
      H4iii=calcSensSpecSeroPrev(ov16_pos_mating_any_mf, 50, 99, probs)
    ) %>% pivot_longer(
      cols=c(H4iii), names_to="Hypothesis", values_to = "ov16_prev"
    ) %>% 
    select(run_num, Hypothesis, ov16_prev, age_groups)
  )

tmp2 <- tmp %>% group_by(run_num) %>% mutate(
      H1iii=calcSensSpecSeroPrev(ov16_pos_l3, 40, 99, probs),
      H2iii=calcSensSpecSeroPrev(ov16_pos_l4, 40, 99, probs),
      H3iii=calcSensSpecSeroPrev(ov16_pos, 40, 99, probs),
      H4iii=calcSensSpecSeroPrev(ov16_pos_mating_any_mf, 50, 99, probs)
    ) %>% pivot_longer(
      cols=c(H1iii, H2iii, H3iii, H4iii), names_to="Hypothesis", values_to = "ov16_prev"
    ) %>% 
    select(run_num, Hypothesis, ov16_prev, age_groups) %>% mutate(
      age_groups = factor(age_groups),
      Hypothesis = factor(Hypothesis)
      ) %>% as.data.frame()

glmer(ov16_prev ~ (1 + Hypothesis | age_groups), data=tmp2, family=poisson)

```


### Calc Residuals
```{r}
use_old_residuals = FALSE
use_cis = FALSE
if (use_old_residuals) {
  filterHypothesesOv16Residuals <- function(data, combineHyp=TRUE, merge_data=TRUE) {
    actual_hyps <- c("Any worm", "L3 exposure", "L4-L5 moult", "Mating worm pair with any mf")
    data <- data %>% filter(Hypothesis %in% actual_hyps)
    if(combineHyp) {
      data <- data %>% mutate(
        Hypothesis = ifelse(Hypothesis == "Mating worm pair with any mf", "H4", "H1-3")
        )
    } else {
      data <- data %>% mutate(
        Hypothesis = case_when(
          Hypothesis == "Any worm" ~ "H3",
          Hypothesis == "L3 exposure" ~ "H1",
          Hypothesis == "L4-L5 moult" ~ "H2",
          Hypothesis == "Mating worm pair with any mf" ~ "H4"
        ),
        Hypothesis = factor(Hypothesis, levels=c("H1", "H2", "H3", "H4"))
      )
    }
    if (combineHyp || merge_data) {
      data <- data %>% 
        group_by(age_groups, Hypothesis) %>% 
        summarise(across(where(is.numeric), mean), .groups="drop")
    }
    return(data)
  }
  calcResiduals <- function(originalData, projection_data, desc, combineHyp=TRUE, merge_data=TRUE) {
    lsr_calculation_data <- merge(projection_data %>% filterHypothesesOv16Residuals(combineHyp = combineHyp, merge_data = merge_data), originalData, by=c("age_groups")) 
    lsr_calculation <- lsr_calculation_data %>%
      mutate(
        mse_value = (
          ((ov16_prev*100) - (ov16_prev_rdt*100))**2 *
            n / total_pop
          )) %>%
      select(Hypothesis, age_groups, mse_value) %>%
      mutate(Descriptor = desc)
    if(merge_data) {
      return(lsr_calculation %>% 
               group_by(Hypothesis, Descriptor) %>%
               summarise(mse=sum(mse_value), .groups="drop")
      )
    }
    
    return(lsr_calculation)
  }
  
  residual_results <- rbind(
    calcResiduals(summarize_gabon_multicountry_data, simulation_summary_elisa_100_mount, "100% Antibody Response"),
    calcResiduals(summarize_gabon_multicountry_data, simulation_summary_elisa_sero_trigger, "Seroreversion on Trigger"),
    calcResiduals(summarize_gabon_multicountry_data, simulation_summary_elisa_sero_no_inf, "Seroreversion on No Infection")
  )
  residual_results$mse <- round(as.numeric(residual_results$mse), 1)
  residual_results$sens_spec <- "1.00_1.00"
  for (elisa_sens_spec_vec in elisa_sens_spec_vec_list) {
    sens_spec_val <- paste(elisa_sens_spec_vec, collapse="_")
    new_results <- rbind(
      calcResiduals(summarize_gabon_multicountry_data, base_k2_list[[sens_spec_val]], "100% Antibody Response"),
      calcResiduals(summarize_gabon_multicountry_data, sero_trigger_k2_list[[sens_spec_val]], "Seroreversion on Trigger"),
      calcResiduals(summarize_gabon_multicountry_data, sero_no_inf_k2_list[[sens_spec_val]], "Seroreversion on No Infection"))
    new_results$mse <- round(as.numeric(new_results$mse), 1)
    new_results$sens_spec <- sens_spec_val
    residual_results <- rbind(residual_results, new_results)
  }
  
  
  residual_results %>% pivot_wider(id_cols=c(sens_spec, Hypothesis), names_from=c(Descriptor), values_from=c(mse)) %>% group_by(sens_spec) %>% mutate(
      across(2:4, ~ ifelse(. == min(.), text_spec(., bold=TRUE), .))
    ) %>% ungroup() %>% kable('html', escape=FALSE) %>% kable_classic() %>% print()
  
  # ---
  
  residual_results_all <- rbind(
    calcResiduals(summarize_gabon_multicountry_data, simulation_summary_elisa_100_mount, "100% Antibody Response", combineHyp = FALSE),
    calcResiduals(summarize_gabon_multicountry_data, simulation_summary_elisa_sero_trigger, "Seroreversion on Trigger", combineHyp = FALSE),
    calcResiduals(summarize_gabon_multicountry_data, simulation_summary_elisa_sero_no_inf, "Seroreversion on No Infection", combineHyp = FALSE)
  )
  residual_results_all$mse <- round(as.numeric(residual_results_all$mse), 1)
  residual_results_all$sens_spec <- "1.00_1.00"
  for (elisa_sens_spec_vec in elisa_sens_spec_vec_list) {
    sens_spec_val <- paste(elisa_sens_spec_vec, collapse="_")
    new_results <- rbind(
      calcResiduals(summarize_gabon_multicountry_data, base_k2_list[[sens_spec_val]], "100% Antibody Response", combineHyp = FALSE),
      calcResiduals(summarize_gabon_multicountry_data, sero_trigger_k2_list[[sens_spec_val]], "Seroreversion on Trigger", combineHyp = FALSE),
      calcResiduals(summarize_gabon_multicountry_data, sero_no_inf_k2_list[[sens_spec_val]], "Seroreversion on No Infection", combineHyp = FALSE))
    new_results$mse <- round(as.numeric(new_results$mse), 1)
    new_results$sens_spec <- sens_spec_val
    residual_results_all <- rbind(residual_results_all, new_results)
  }
  
  
  residual_results_all %>% pivot_wider(id_cols=c(sens_spec, Hypothesis), names_from=c(Descriptor), values_from=c(mse)) %>% group_by(sens_spec) %>% mutate(
      across(2:4, ~ ifelse(. == min(.), text_spec(., bold=TRUE), .))
    ) %>% ungroup() %>% kable('html', escape=FALSE) %>% kable_classic() %>% print()
  
  # ---
  
  residual_results <- rbind(
    calcResiduals(summarize_gabon_multicountry_data, simulation_summary_elisa_100_mount_k3, "100% Antibody Response", combineHyp = FALSE),
    calcResiduals(summarize_gabon_multicountry_data, simulation_summary_elisa_sero_trigger_k3, "Seroreversion on Trigger", combineHyp = FALSE),
    calcResiduals(summarize_gabon_multicountry_data, simulation_summary_elisa_sero_no_inf_k3, "Seroreversion on No Infection", combineHyp = FALSE)
  )
  residual_results$mse <- round(as.numeric(residual_results$mse), 1)
  residual_results$sens_spec <- "1.00_1.00"
  for (elisa_sens_spec_vec in elisa_sens_spec_vec_list) {
    sens_spec_val <- paste(elisa_sens_spec_vec, collapse="_")
    new_results <- rbind(
      calcResiduals(summarize_gabon_multicountry_data, base_k3_list[[sens_spec_val]], "100% Antibody Response", combineHyp = FALSE),
      calcResiduals(summarize_gabon_multicountry_data, sero_trigger_k3_list[[sens_spec_val]], "Seroreversion on Trigger", combineHyp = FALSE),
      calcResiduals(summarize_gabon_multicountry_data, sero_no_inf_k3_list[[sens_spec_val]], "Seroreversion on No Infection", combineHyp = FALSE))
    new_results$mse <- round(as.numeric(new_results$mse), 1)
    new_results$sens_spec <- sens_spec_val
    residual_results <- rbind(residual_results, new_results)
  }
  
  
  
  
  
  residual_results %>% pivot_wider(id_cols=c(sens_spec, Hypothesis), names_from=c(Descriptor), values_from=c(mse)) %>% group_by(sens_spec) %>% mutate(
      across(2:4, ~ ifelse(. == min(.), text_spec(., bold=TRUE), .))
    ) %>% ungroup() %>% kable('html', escape=FALSE) %>% kable_classic() %>% print()
}

calc_resids <- function(base, no_inf, trigger, kE) {
  resids = c()
  for(sens_spec in elisa_sens_spec_vec_list) {
    print(sens_spec)
    new_result <- rbind(
        custom_calc_resid(summarize_gabon_multicountry_data, data_manip_resid(base, sens_spec), paste0("100% Antibody Response ", "kE = ", kE)),
        custom_calc_resid(summarize_gabon_multicountry_data, data_manip_resid(no_inf, sens_spec), paste0("Seroreversion on no infection", "kE = ", kE)),
        custom_calc_resid(summarize_gabon_multicountry_data, data_manip_resid(trigger, sens_spec), paste0("Seroreversion on Trigger", "kE = ", kE))
    )
    new_result$sens_spec <- paste0(sens_spec, collapse=", ")
    if (length(resids) == 0) {
      resids <- new_result
    } else {
      resids <- rbind(
        resids,
        new_result
      )
    }
  }
  return(resids)
}

process_resids <- function(resids, display_cis) {
  final_resids <- resids %>%
    group_by(Descriptor, Hypothesis, sens_spec) %>%
    summarise(
      sample_mean = mean(mse),
      sample_varience = var(mse),
      se = sqrt(sample_varience / n_distinct(run_num)),
      lower_bound = sample_mean - 1.96 * se,
      upper_bound = sample_mean + 1.96 * se,
      .groups="drop"
    ) %>%
    mutate(
      output_val = paste0(round(sample_mean, 2)),
      Hypothesis = factor(Hypothesis, levels=c("H1", "H2", "H3", "H4")),
      sens=substr(sens_spec, 1, 3),
      spec=substr(sens_spec, 6, 9)
    ) 
  if(display_cis) {
    final_resids <- final_resids %>% 
      mutate(
        output_val = paste0(round(sample_mean, 2), " (", round(lower_bound, 2)," - ", round(upper_bound, 2),")")
      )
  }
  return(
    final_resids %>% 
      select(Descriptor, Hypothesis, spec, sens, output_val) %>%
      pivot_wider(id_cols=c(spec, sens, Hypothesis), names_from=c(Descriptor), values_from=c(output_val)) %>% group_by(spec, sens) %>% 
      mutate(
        across(2:4, ~ {
          first_num <- as.numeric(str_extract(., "^\\d+\\.\\d+"))
          min_val <- min(unlist(across(2:4, ~ as.numeric(str_extract(., "^\\d+\\.\\d+")))), na.rm = TRUE)
          ifelse(grepl(min_val, .),
                 text_spec(., bold=TRUE), 
                 .)
        })
      ) %>% 
      ungroup() %>% 
      arrange(desc(spec), sens, Hypothesis) %>% kable('html', escape=FALSE) %>% kable_classic() %>% print())
}

resids_k2 <- calc_resids(summarizeSimulatedGabon_elisa_100_mount, summarizeSimulatedGabon_elisa_sero_no_inf, summarizeSimulatedGabon_elisa_sero_trigger, "0.2")
process_resids(resids_k2, FALSE)
process_resids(resids_k2, TRUE)

resids_k3 <- calc_resids(summarizeSimulatedGabon_elisa_100_mount_k3, summarizeSimulatedGabon_elisa_sero_no_inf_k3, summarizeSimulatedGabon_elisa_sero_trigger_k3, "0.3")
process_resids(resids_k3, FALSE)
process_resids(resids_k3, TRUE)
```


